name: Create  a comment on new issues 2

on:
    issues:
      types: [opened]
jobs:
    comment-with-action:
      runs-on: ubuntu-latest
      steps:
        - name: "dump github context"
          run: echo 's{{ toJSON(github.event)}}' | jq
          shell: bash
